name: pixmap
description: >
  A simple sprite library for Dart web applications.
version: 0.1.0
authors:
  - Matan Lurey <matanl@google.com>
homepage: https://github.com/matanlurey/pixmap

environment:
  sdk: ">=1.22.0 <2.0.0"

dev_dependencies:
  collection: ^1.0.0
